### PR TITLE
fix serverside rendering

### PR DESCRIPTION
**Pull request by peter-mouland**
@peter-mouland @alex.florisca : ensure `keystroke` module is only used client-side

 - [x] update dependencies
 - [x] add server-side rendering
 - [x] add npm script to load docs through server
 - [x] setup functional testing
 - [x] add functional test for site
 - [x] integrate into CI

### CODE REVIEW

**Comment by nowarkdev** [comment]
@ariley90 👎 We should include a test which if nothing else just documents why we don't import the keystroke module in the regular way so it doesn't regress once we forget why! I think this will include test setup for both server and client rendering which in the long run will be a big win!

**Comment by bentidy** [comment]
Agreed @ariley90 

- @bdo @ldabiralai

**Comment by peter-mouland** [comment]
@bentidy @ariley90 @bdo @ldabiralai

webdriverio functional testing has been added. this is cool. :dancer:

**Comment by peter-mouland** [comment]
fixes #14

**Comment by andrewmerrell** [comment]
:+1:

**Comment by ariley90** [comment]
@peter-mouland Do you have experience with using webdriveio? I'm trying to add a test around the modal before I give it the thumbs up. I'm struggling to check that the modal has opened to begin the test. He's the snippet which I've tried from their site.
```
client.init()
      .url(wdio.baseURL + '/')
      .click('#modalCta')
      .isVisible('.nowtv-modal.visible'.then(function(isVisible){
        expect(isVisible).to.be.true;
      })
```
http://webdriver.io/guide/usage/transferpromises.html

isVisible always returns false.

Otherwise looks good!

**Comment by peter-mouland** [comment]
@ariley90 
good checking :)

So to get your code working i had to add your new id to the model button in the Docs code.  I then updated the snippet to be this:
```
    client.init()
      .url(wdio.baseURL + '/')
      .click('#modalCta')
      .isVisible('.now-modal.visible').then(function(isVisible){
        expect(isVisible).to.equal(true);
        done()
      });
```

**Comment by ariley90** [comment]
Hmmm that still doesn't seem to work on circle or my machine locally? Anything unique about your setup?

**Comment by ariley90** [comment]
I can finally give you a 👍

Only potential issue I could see is phantom2 not playing nicely with El Capitan but Chrome worked great for me locally.

**Comment by peter-mouland** [comment]
@ariley90 i see you got the browser to close when the test is finished. wicked :+1: 

I guess to finish it off nicely we could incoporate the [selenium standalone](https://github.com/vvo/selenium-standalone#seleniumstartopts-cb) packing into our setup 
and call something like : 
```javascript
var selenium = require('selenium-standalone');

selenium.start({})
```

**Pull request merged**
