### PR TITLE
@benstokoe|@tristancooper: Selenium standalone needs to be dependency

### PR DESCRIPTION
**Pull request by nowarkdev**
For postinstall script

### CODE REVIEW

**Comment by peter-mouland** [comment]
good spot - does this now mean that selenium gets installed on all machines that have a dependency on the react toolkit?

Should we instead just add this in the `Prerequisites` in contributing.md?
i.e.
```md
Selenium is required for tests :

 * npm run selenium:install
```

**Comment by nowarkdev** [comment]
Some people did it into master without a pull request...

**Comment by nowarkdev** [comment]
@bdo @rogerfranklin2

**Comment by peter-mouland** [comment]
@bdo @rogerfranklin2 the [CONTRIBUTING.md](CONTRIBUTING.md) file needs updating as suggested above

**Pull request closed without merging**
