### PR TITLE
Also children type node for Accordion Item

### PR DESCRIPTION
**Pull request by nowarkdev**
@benstokoe|@tristancooper

### CODE REVIEW

**Comment by peter-mouland** [comment]
what does this mean?

**Comment by nowarkdev** [comment]
When using an AccordionItem the prop types currently on it don't work when passing in a single object as a child. Using PropTypes.node is better for this

**Comment by peter-mouland** [comment]
:+1:

**Comment by nowarkdev** [comment]
@roryp2 :thumbsup:

**Pull request merged**
