### PR TITLE
Enzyme tests

### PR DESCRIPTION
**Pull request by rogerfranklin2**
Made a start changing the tests to enzyme (and added very few).

Still got to do accordion and toggle-button tests

Let me know what you think

### CODE REVIEW

**Comment by peter-mouland** [comment]
what have you noticed that we gain with enzyme, is it just cleaner code, or is it more than that?

**Comment by alexjfno1** [comment]
Sorry I'm going to be a picky here but I thought that a pull request had to get two thumbs up before it was merged?

I don't have an issue with the code but if we have guidelines should we follow them even if it is a small change?

**Comment by rogerfranklin2** [comment]
It was reviewed as a group and merged as a group at the meeting you didn't attend today

**Comment by alexjfno1** [comment]
Whoops sorry didn't realise that :+1:

**Pull request merged**
