### PR TITLE
@rogerfranklin2 @ldabiralai Reivising logic around the arrow pointing…

### PR DESCRIPTION
**Pull request by rogerfranklin2**
Small alignment issue with the tip of the tooltip, now minus half the width of the arrowtip

just a patch nothing breaking

### CODE REVIEW

**Comment by nowarkdev** [comment]
:+1:

**Comment by nowarkdev** [comment]
screen shot 2016-02-24 at 10 44 20

:-1: 

@peterthompson @andhapp

**Comment by peter-mouland** [comment]
is this meant to be shifting the content down, shouldn't it be positioned absolutely?

**Comment by tomatau** [comment]
what is |||-----|-----|||?

**Comment by bentidy** [comment]
|||-----|-----||| is to see that its pointing to the middle

**Comment by bentidy** [comment]
Yes its supposed to push the content down @rogerfranklin2 @ldabiralai

**Comment by nowarkdev** [comment]
:+1: 

@peterthompson @andhapp

**Pull request merged**
