### PR TITLE
@andrewmerrell adding eslint and fixing lint errors

### PR DESCRIPTION
**Pull request by andrewmerrell**
Adding eslint rules as per discussion on #16 fixed up the linting issues as a result too.

### CODE REVIEW

**Comment by peter-mouland** [comment]
great :+1:

**Comment by nowarkdev** [comment]
If we are going to do this, it's probably a good idea to use the same linting rules that are present in the global navigation, or vice versa.

@ldabiralai

**Comment by peter-mouland** [comment]
@andrewmerrell have you a preference over which eslint to use?

**Comment by peter-mouland** [comment]
@ldabiralai I've updated the rules to match the navigation project. They're more strict, but in a good way i.e. doesn't allow mixing of tabs and spaces

**Comment by bentidy** [comment]
@peter-mouland looks good :+1:

- @ldabiralai

**Pull request merged**
