### PR TITLE
update button component to use base-toolkit

### PR DESCRIPTION
**Pull request by peter-mouland**
* updated babel preset stage to `0` (to allow property initialisers)
 * moved the spec to live next to the component (which makes it easier to spot missing unit tests)
 * updated docs 

**Before**

screen shot 2016-01-05 at 16 32 22
screen shot 2016-01-05 at 16 32 34

**after**
screen shot 2016-01-05 at 16 32 40

### CODE REVIEW

**Comment by nowarkdev** [comment]
@benstokoe|@tristancooper: 👍

**Comment by tomatau** [comment]
Re: Getting to work on heroku --  we're putting this on NPM now so it shouldn't have the same issues. Are you talking about adding the NPM_TOKEN as an environmental setting? I've added this note now.

Re: example .babelrc -- it's advised that this is setup using regex in the babel options which isn't available in a .babelrc. The example I've put in for the babel/runtime is babel5 style. I think teaching people how to use babel is out of scope for this readme.

I've added more example and detail about the preferred usage of babel/register for client and added the query options in the webpack example for client.

**Comment by bentidy** [comment]
Just a few small issues/questions before this is ready from my point of view:

- It doesn't look like this supports passing through an onClick prop to the button anymore.
- Also, in the toolkit.sass we're still importing the ButtonStyles, which have now been removed.
- Is webpack-dev-server a dependency? Should it not be a devDependency?

Also, is the direction you want to take to write tests in the component folder directly, rather than in it's own test folder in the root?

@ldabiralai

**Comment by peter-mouland** [comment]
@ldabiralai wicked, we've now:
 * added a test to prove onClick still works.  
 * removed the reference to buttons.scss from the toolkit
 * and webpack-dev-server is a devDependency :dancer:

**Comment by bentidy** [comment]
Awesome, looks good :+1: 

@ldabiralai

**Pull request merged**
