### PR TITLE
Merge styleguide toolkit

### LINKED ISSUE #100: Move the React-Toolkit into this Styleguide repo
Alright, so this idea might be completely undoing what's already been done... but just go with me here...

**Problems we have right now**

- **Updating the styleguide and toolkit is a huge pain**. 
  - Especially for breaking changes, there's PRs all over the place
  - Things going in and out of sync it's easy to forget to update both styleguide and toolkit at the same time
  - Communicating changes that refer to both projects is also a bit of a hassle.
  - Double release notes, double npm publishes, double docs, double tests (when we do some css regression) it's too easy to forget one of these things.
- **Where to put things** should the toolkit be requiring the styles? Should the styleguide have the fonts? Should the toolkit have icons? With both repos, it's unclear and very subjective about where assets should be living.
- **Accommodating everyone twice** with so many ways to use the combination of the two projects in your app (cdn, import the dist compiled output, import src with various compiler config settings).. it's getting fairly hairy to accommodate all of these options in both projects. And do we even need to accommodate all of these approaches? E.g. Letting apps import the full dist means they're often requiring a bunch of css or javascript that they'll never use.

I'm suggesting we just move all the toolkit components into the styleguide. One place to update. One place to put things. One set of scripts, tests, compilation and documents to maintain.

**New Problems**

- **consumers of the styleguide don't always need the react components** - So what? They don't need to require them.
- **importing it all would be very large** - So we should discourage this 'import it all' approach, and instead encourage consumers to only import what they need instead.
- **Why only React? Should we then support other component types such as angular?** - Consumers might be using the styleguide for angular directives or whatever... they already will need to update those directives when we do styleguide breaking changes anyway... So if those consumers see a benefit to putting them in here... seems ok to me! It could even encourage other teams to get more involved in the global styleguide... There are other downsides to this but I think the benefits greatly outweigh the cons.
- **Other problems?** - You tell me.

### PR DESCRIPTION
**Pull request by rogerfranklin2**
fixes #100 

We have merged the two projects. Currently we have focused on the source and actual code, the docs are not finished yet, we're planning to do this after this has merged, and as a new PR.

Could be an idea to change the repos name after merging too?

We've created a short upgrade guide below, feel free to make any suggestions if we've missed anything.

### Consuming react components from source
Old:
```javascript
import Button from '@nowtv/nowtv-react-toolkit/src/Button/Button.react'
```
New:
```javascript
import Button from '@nowtv/nowtv-react-toolkit/react-components/src/Button/Button.react'
```

### Consuming styleguide styles from source
Old:
```sass
@import '~@nowtv/nowtv-styleguide/src/components/button'
```
New:
```sass
@import '~@nowtv/nowtv-react-toolkit/styleguide/components/button'
```

### Consuming JS from react toolkit dist
```javascript
import Toolkit from '@nowtv/nowtv-react-toolkit'
```
### Consuming CSS from dist
```javascript
import '@nowtv/nowtv-react-toolkit/dist/styleguide.css'
```

@rogerfranklin2 @ldabiralai

### CODE REVIEW

**Comment by tomatau** [comment]
Why is this in the toolkit when the main focus is styles? Not every team cares about react stuff - the project name should probably reflect that.

**Comment by tomatau** [comment]
What about consuming fonts and icons?

**Comment by benstokoe** [comment]
It doesn't matter which one we merge in to the other. We can change the name to reflect it

**Comment by benstokoe** [comment]
More people use react for it anyway. A good name will be nowtv-toolkit... Like it used to be called.... Before we split it up.. :)

**Comment by rogerfranklin2** [comment]
Agree with Ben or maybe nowtv-web-toolkit to match the navigation.

We did mention it at the top of the PR that we might want to change the name but that doesn't need to be done first

Everything that was in the dist of the styleguide is now is the dist of the react toolkit so for fonts it would be:

```javascript
import '@nowtv/nowtv-react-toolkit/dist/fonts.css'
```

We don't consume icons from toolkit. How do you do it at the moment ? @tomatau

**Comment by tomatau** [comment]
Name change sounds good, I missed that when reading the PR.

With icons, we don't import them directly, we have to modify how we consume individual component styles to take into account any icons those styles depend on.

E.g.
```scss
$icon-path: "~@nowtv/nowtv-styleguide/src/icons";
@import "~@nowtv/nowtv-styleguide/src/components/accordion";
```

There's also some styles in there that use `$icon` instead of `$icon-path` for some reason.

I'm guessing there's still the requirement to also import the `styleguide/base/base.scss` before importing any specific component styles too.

**Comment by rogerfranklin2** [comment]
Icons would become:

```scss
$icon-path: "~@nowtv/nowtv-react-toolkit/styleguide/icons";
@import "~@nowtv/nowtv-react-toolkit/styleguide/components/accordion";
```

**Comment by nowarkdev** [comment]
@roryp2 @PLAGR34GTT 

Looks good. We should definitely rename it at some point soon.

What are we going to do about current pull requests on the styleguide? Will we just merge them in after? Or replicate them in this repo?

It looks good though and shouldn't be too much of a problem for teams to migrate to once it is merged :+1:

**Comment by rogerfranklin2** [comment]
As we will be waiting till tuesdays 2pm meeting to merge this in, carry on with the normal commits/merges on toolkit and styleguide and before we merge this in we will get the latest version of the styleguide.

Would be good to go into tuesdays meeting with no outstanding pull requests but we will see how it goes.

**Comment by nowarkdev** [comment]
:+1: @rob-howe

**Comment by peter-mouland** [comment]
hey, I've noticed a couple things, not sure if i've missed something in the code or not...

 * There seems to be a rouge file `src/components/Accordion/AccordionItemContent.spec.js` (using the previous file structure). Not sure if this should be deleted or moved with the others?
 * It looks like there is still a dependency on `@nowtv/nowtv-styleguide`, which i guess isn't needed now?
 * I couldn't see where the docs are for the non-react components, like buttons and inputs etc?
 * the webpack could made a bit more DRY but merging the two 'entry' arrays' and using `include` and `exclude`for the svg module loaders (if they still need to be loaded in two different ways).
 * I've tried to run this locally, but get the following error, did i miss a step (i did do an npm i!)?
   * ` Cannot resolve 'file' or 'directory' ./icons/red-chevron-down.svg` 

After going through it with the group, we also agreed:
 * we should keep the tests with the components.
   * we didn't mention feature tests, but if we are keeping them with the components, then maybe changing the suffix to `.feature.js` rather than `.spec.js` would help the test runner globbing.  what do you think?
 * it would be good to have a single `/src` directory which has a `/styles` subdirectory and the react stuff in here
 * probably not necessary to have a `react-components` directory which then contains `src/components` directory, just `react` or `react-components` would be fine.

**Comment by peter-mouland** [comment]
Just spotted that this is to go into master.  Do we want this to go into a `v2-rc type` branch or would that be overkill?

Just thinking about the reasons we have done this for the style-guide. maybe they don't apply here, but worth thinking about....

**Comment by nowarkdev** [comment]
@peter-mouland 

We've moved the spec and removed the dependency on the styleguide.

We did mention that the docs weren't finished, currently they don't include anything about non-react components but we were planning to do this after the merge was complete.

We decided to keep the webpack.config.js separate for now just because if they're separate then we felt it was easier to understand, if you want to discuss this we can do, but I don't think we should let this block the PR.

Just added red-chevron-down, looks like we missed adding that to git.

@ldabiralai @rogerfranklin2

**Comment by peter-mouland** [comment]
cool - agreed, those questions shouldn't block this PR.

cool, thanks for the update - still can't run the project though as the webpack config hasn't been udpated.

```
ERROR in multi styleguide
    Module not found: Error: Cannot resolve 'file' or 'directory' ./styleguide/styleguide.scss in /Users/Mac/projects/nowtv-react-toolkit
     @ multi styleguide
    
    ERROR in multi fonts
    Module not found: Error: Cannot resolve 'file' or 'directory' ./styleguide/fonts.scss in /Users/Mac/projects/nowtv-react-toolkit
     @ multi fonts
```

The question around versioning is valid though.  Renaming this project to 'nowtv-web-toolkit' wont allow us to roll down to a v0.0.1; it would have to be a new repo.  So for now, as we've agreed the next major version bump should be stable, this should be v2-rc-1at most.  We just need to decide if it should go into master (which would block further bug fixes) or stay on a branch.  I don't mind as we want these latest changes and will be going to the bleeding edge no mater where it lives!

**Comment by ldabiralai** [comment]
Why would we not be able to go down to a version 0.0.1 or 0.1.0 or whatever version we eventually decide?

**Comment by peter-mouland** [comment]
feels wrong to remove the existing git-tags. i guess since everyone is importing via npm it's not actually that big a deal, but It's not the way git/npm is intended to work (i.e. going backwards) so i'm not sure if there would be any side-effects?

**Comment by peter-mouland** [comment]
closing this as this is available at the new repo https://github.com/sky-uk/nowtv-web-toolkit

**Pull request closed without merging**
