### PR TITLE
Fixing accordion error on the browser

### PR DESCRIPTION
**Pull request by rogerfranklin2**
The accordion is currently broken for people not rendering on the server. 

When using the accordion on the browser you will get the error 
```
Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

This is a problem with the cloning of the element and the use of the refs so we have changed it back to how it was done before.

As you will see there are a lot of if's for the extended accordion, we know that this solution is not the best and we are going to refactor and separate these into 2 separate accordion components but for now as a first step to fix it for most teams

### CODE REVIEW

**Comment by peter-mouland** [comment]
there are a lot :s 
are the if's really based on accordion type or on rendering (browser vs server)?

Is there a client-side test that we can add to this?

**Comment by tomatau** [comment]
We ran into this problem on the docs as 2 Reacts were being loaded on the page. On the docs we just made sure only one version of react was loaded and the client side render worked fine.

**Comment by peter-mouland** [comment]
lets see if we can get [pr 82](https://github.com/sky-uk/nowtv-react-toolkit/pull/82) to see if it fixes the errors you found before going forward with these changes...

**Comment by ldabiralai** [comment]
Closing this as it should be fixed by #82

**Pull request closed without merging**
