### PR TITLE
Allow links to look like buttons

### PR DESCRIPTION
**Pull request by peter-mouland**
>**note:** needs the latest `nowtv-toolkit` from the `links-as-buttons` [branch/pr](https://github.com/sky-uk/nowtv-toolkit/pull/13)

**New link which looks like a button**
screen shot 2016-01-07 at 17 01 42

### CODE REVIEW

**Comment by alexjfno1** [comment]
I know there wasn't a test for the button component before but would this be the time to add one as now there is logic in it?

**Comment by peter-mouland** [comment]
good spot @alexjfno1, we do have one - clearly forgot to add it to the PR

**Comment by nowarkdev** [comment]
👍@tristancooper

**Comment by alexjfno1** [comment]
@peter-mouland Did you say you had a test?

**Comment by alexjfno1** [comment]
:+1:

**Pull request merged**
