### PR TITLE
Adding release tasks

### PR DESCRIPTION
**Pull request by alexjfno1**
Adding tasks to NPM to make it easier to publish the module.

It checks that you are logged into NPM as NowTV first before publishing.

### CODE REVIEW

**Comment by peter-mouland** [comment]
cool - great update.
Do we still need to log into npm now it's public?

**Comment by alexjfno1** [comment]
Im not 100% sure but I would imagine you do otherwise anybody would be able to push a new version.

**Comment by peter-mouland** [comment]
good point!

**Comment by ldabiralai** [comment]
Ideally this should have `git push` on the end too as `npm version` bumps the version in package.json and commits it after too.

Otherwise this could cause the package.json becoming out of sync with the version published on npm

**Comment by alexjfno1** [comment]
I did think about that but it might push stuff unexpectedly but its up for debate. I think that I need to add something to the docs anyway and maybe I could state there that you must push after the command is run.

**Comment by ldabiralai** [comment]
:+1:

**Comment by peter-mouland** [comment]
should the release docs go into the contributing.md?

then we can keep the README.md for how to use/consume the package

**Comment by alexjfno1** [comment]
I've moved it :)

**Comment by peter-mouland** [comment]
:+1:

**Pull request merged**
