### PR TITLE
remove `/dist` from git

### LINKED ISSUE #20: `dist` should be ignored from git

### PR DESCRIPTION
**Pull request by peter-mouland**
fixes #20

### CODE REVIEW

**Comment by alexjfno1** [comment]
We are currently using the dist version of the scss in My Account. Do we get it from here now `src/toolkit.sass`?

**Comment by peter-mouland** [comment]
dist should still be available when the package is installed from npm.

**Comment by rogerfranklin2** [comment]
As this will be a breaking change for the myaccount guys we should wait till they move to using the module rather than the repo.

Other than that should be fine to go

**Comment by alexjfno1** [comment]
If the dist remains in the NPM module it won't break us :)

**Comment by peter-mouland** [comment]
great - will merge.

**Pull request merged**
